{
    # directory and file setting to apply genConfig
    'genConfig': {
         'dir': [ '/domoticz':        [ './domoticz/script_device_security2Warning.lua',
                                        './domoticz/script_time_securityStatus.lua' ],
                  '/alarmController': [ './alarmController/config.h']
         ],
         'ignore' : [ './domoticz/.idea','/venv'],
    },

    # values
    'config': { #AlarmController Sensor
      # Wifi configuration
        'wifiSSID': 'myWifiName',
        'wifiPassword': 'MyWifiPassword',

      # Other The Air update Configuration
        'otaHost': 'esp8266-alarmController',
        'otaPassword': 'MyOTAPassword',
        'otaPort': '8266',

      # Web Controller
        'adminName': 'admin',
        'adminPwd': 'MyHttpPassword',
	
      # Jeedom setting
        'jeedomURL' :  'http://192.168.1.54',
        'jeedomApiKey': 'KDLAZ?EKqsdk4JzheAQNsdkajhzeSQLD',
        'controllerServerPort': '80',
        'jeedomCmdId': '243',
	
      #Domoticz Scripts
        'securityCtrlUrl': 'http://192.168.0.130',
        'armedDelaySec': '30',  # delay for transition Arming->Armed
        'faultDelaySec': '30',  # delay to return Warn1->Armed
        'alarmDelaySec': '10',  # delay for transition Warn2->Alarm
        'rearmDelaySec': '300', # delay after Alarm->Armed
        'blindDelaySec': '10',  # delay of not taking into account the activation of the same device
    }
}